//  <autogenerated>
//      This code was generated by a tool.
//      Xamarin Excalibur Version: 1.0.5809.35947
//  </autogenerated>

[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.Alert))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.AlertDescription))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.AlertLevel))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.CertificateValidationHelper))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.CipherAlgorithmType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.CipherSuiteCode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.ExchangeAlgorithmType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.HashAlgorithmType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.IBufferOffsetSize))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.ICertificateValidator))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.IMonoSslStream))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.IMonoTlsContext))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.IMonoTlsEventSink))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoEncryptionPolicy))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoLocalCertificateSelectionCallback))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoRemoteCertificateValidationCallback))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoSslPolicyErrors))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoTlsConnectionInfo))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoTlsProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoTlsProviderFactory))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.MonoTlsSettings))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.TlsException))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.TlsProtocolCode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.TlsProtocols))]
[assembly: System.Runtime.CompilerServices.TypeForwardedToAttribute(typeof(Mono.Security.Interface.ValidationResult))]

